language: node_js
node_js:
- '8'

env:
  global:
  - secure: pLF4tPhyB8D+5ooj9f5VaOKGjfW2msO4QmDVIOkALrbrZ12isbA/PAuRNS2lqV97hCaFrxjrzHuxTpWgRF3DMdeOW4g3sJ/zSY3kpU4qSQ9eZWzQrqjHnaU/mOnn5RRg/61yvL5o8ITQ2ilKP2jdmoXuR73g59nPAp18zLGnXYc=
  - secure: ipguI7zt0Sky5AIoWekk4NhH8W62rTxJzt/xjXACWx8DKx//o8SURYG2ARf+sVJR3m+xNDixen1K/3hlGonf2btJU8ZklDCnnMGkmuAmuXvFvB2fKf5Xe6fefWJggAhSQJ8NjgXCsZZ4czQ93m9B+zSpB2pdIq1NJXmoeW5E0kk=
  - secure: h+VU+tGEwvnPYFJsPbddmYFHPAyNUh+Nf5Dab+SW3wY284kajKrsjHkZdq/Wht6TXcR032HXqPyDxWNBYS/8dK5oImmFIKYvUYacu0ZO2LY3HJLN6BPpp+FNJhjTQ9C7NetH5yqmyU0ooZz+CtZdIx1i1PWzxIr+a1E8ogrLgik=
  - secure: MxVTrv/Wri2LRMG8fn2H5GEufgXfTmZgGfFpQw9zCkjI6oG4rIizha7IjHBw+7QXuLw6x5T0bqnmXFdhNK5kEiwiBhMins4/93FxH6qIA78FNI6RdAgj9EoCRVM/hmFPq2EszsYVOyqOrbASDnt+uWDNOO8oVrZdmIS/LCKv/V8=

before_install: npm install -g grunt-cli

install:
- npm install

test:
- provider: script
  script: npm test

deploy:

- provider: script
  script: grunt firefoxBeta && grunt deployFirefoxBeta
  repo: Ajnasz/hupper
  skip_cleanup: true
  on:
    tags: true
    condition: tag =~ /^v?\d+\.\d+\.\d+-\d+$/

- provider: script
  script: grunt firefox && grunt deployFirefox
  repo: Ajnasz/hupper
  skip_cleanup: true
  on:
    tags: true
    condition: tag =~ /^v?\d+\.\d+\.\d+$/
